name: elapser
description: A new Flutter project.
publish_to: "none"
version: 0.0.1+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_layout: ^1.0.7+2 # Execute code after first layout
  auto_size_text: ^2.1.0 # Automatically resizes text to fit perfectly within its bounds.
  cupertino_icons: ^0.1.3
  enum_to_string: ^1.0.9
  equatable: ^1.1.1 # Needed for flutter_bloc
  flutter_bloc: ^4.0.0 # Widges to implement BLoC pattern
  flutter_localizations: # Flutter SDK for internalization
    sdk: flutter
  flutter_modular: ^1.2.7+1 # Smart project structure with dependency injection and route management
  mode_theme:
    git:
      url: https://github.com/GitHubStuff/mode_theme.git
  tracers:
    git:
      url: https://github.com/GitHubStuff/tracers.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - languages/en.json
